/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import UI.Email;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import static javax.swing.text.html.HTML.Attribute.DATA;

/**
 *
 * @author Marina
 */
public class BALANCEINQUIRY extends javax.swing.JFrame {

    /**
     * Creates new form BALANCEINQUIRY
     */
    public BALANCEINQUIRY() {
        initComponents();
    }

     
    public BALANCEINQUIRY(String us) {
        initComponents();
        user.setText(us);
    }
     public String sendMail(String Email,String Password,String ToEmail, String Subject,String Text){

	String Msg;
    
        final String username = Email;
        final String password = Password;

        Properties props = new Properties();
        props.put("mail.smtp.auth", true);
        props.put("mail.smtp.starttls.enable", true);
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(Email));//ur email
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(Email));//u will send to
            message.setSubject(Subject);
            message.setText(Text);
            Transport.send(message);
            Msg="true";
    	    return Msg;

        } catch (Exception e) {
            return e.toString();
        }
    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NULL1 = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        serice = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        avail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SERVICE = new javax.swing.JLabel();
        SERVICE1 = new javax.swing.JLabel();
        TX1 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        balanc = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Email = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        Balance = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        NULL2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(9, 9, 9, 9, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        NULL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL1);
        NULL1.setBounds(1330, 110, 160, 150);

        CANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });
        jPanel3.add(CANCEL);
        CANCEL.setBounds(40, 600, 160, 150);

        serice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        serice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sericeActionPerformed(evt);
            }
        });
        jPanel3.add(serice);
        serice.setBounds(1330, 590, 160, 150);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton10);
        jButton10.setBounds(40, 110, 160, 150);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("-");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1290, 610, 50, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(190, 470, 43, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(190, 630, 43, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("-");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(190, 150, 50, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("-");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(190, 310, 43, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(1290, 160, 50, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("-");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(1290, 450, 50, 100);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("-");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(1290, 310, 50, 50);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        avail.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        avail.setForeground(new java.awt.Color(204, 255, 204));
        jPanel4.add(avail);
        avail.setBounds(270, 290, 520, 71);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pops.jpg"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(250, 20, 570, 140);

        SERVICE.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        SERVICE.setForeground(new java.awt.Color(255, 255, 204));
        SERVICE.setText("BALANCE");
        jPanel4.add(SERVICE);
        SERVICE.setBounds(860, 440, 190, 70);

        SERVICE1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        SERVICE1.setForeground(new java.awt.Color(255, 255, 204));
        SERVICE1.setText("EMAIL INFORMATION");
        jPanel4.add(SERVICE1);
        SERVICE1.setBounds(630, 600, 420, 70);

        TX1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        TX1.setForeground(new java.awt.Color(255, 255, 204));
        TX1.setText("CANCEL");
        jPanel4.add(TX1);
        TX1.setBounds(40, 600, 250, 70);

        balance.setBackground(new java.awt.Color(204, 204, 204));
        balance.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        balance.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(balance);
        balance.setBounds(440, 360, 240, 90);

        balanc.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        balanc.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(balanc);
        balanc.setBounds(360, 360, 110, 90);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/glossy.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 1050, 710);

        user.setText("user");
        jPanel4.add(user);
        user.setBounds(860, 130, 110, 40);

        jScrollPane1.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(540, 410, 8, 22);
        jPanel4.add(Email);
        Email.setBounds(930, 230, 0, 0);
        jPanel4.add(Pass);
        Pass.setBounds(930, 150, 0, 0);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(223, 31, 1070, 730);

        Balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        Balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceActionPerformed(evt);
            }
        });
        jPanel3.add(Balance);
        Balance.setBounds(1330, 430, 160, 150);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton9);
        jButton9.setBounds(40, 430, 160, 150);

        NULL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL2);
        NULL2.setBounds(1330, 270, 160, 150);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(1293, 11, 210, 770);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton7);
        jButton7.setBounds(40, 270, 160, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(9, 11, 220, 770);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 10, 1090, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 730, 1070, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed

        this.setVisible(false);
        new CANCEL().setVisible(true);
        dispose();
    }//GEN-LAST:event_CANCELActionPerformed

    private void sericeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sericeActionPerformed
       Connection con=null;
        PreparedStatement mystmt=null;
        ResultSet rs=null;
        String u;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull", "root", "");
            mystmt = con.prepareStatement( "Select * from atmm where username=?");
            mystmt.setString(1, user.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                balance.setText(rs.getString("Balance"));
                
                Email.setText(rs.getString("EmailID"));
                Pass.setText(rs.getString("EmailPassword"));
                String EMAIL = Email.getText();
                String PW=Pass.getText();
                String To=Email.getText();
                String SUBJECT="BANK OF SJC .. BALANCE";
                String MESGE="Dear Customer,we have processed your request on Balance INFO of your A/c no. xxxxxxxxxx, Available balance is RS. "+balance.getText()+"\n\n\nTHANK YOU  \n\nREGARDS SWIZZ BANK";
        
        String DATA=new Email().sendMail(EMAIL, PW, To, SUBJECT, MESGE);
        System.out.println(DATA);
        this.setVisible(false);
        new CANCEL().setVisible(true);
        if(DATA.equals("true")){
        
            JOptionPane.showMessageDialog(this,"Your Balance Information Has been Sent to your registered Email !!!");
        
        }else{
        
            JOptionPane.showMessageDialog(this,"An Error Occured While Sending Your Balance information To your Email We'll Quickly Sort the problem ","Error",JOptionPane.ERROR_MESSAGE);
        }
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        } 
    }//GEN-LAST:event_sericeActionPerformed

    private void BalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceActionPerformed
       Connection con=null;
        PreparedStatement mystmt=null;
        ResultSet rs=null;
        String u;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull", "root", "");
            mystmt = con.prepareStatement( "Select * from atmm where username=?");
            mystmt.setString(1, user.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                balance.setText(rs.getString("Balance"));
                avail.setText("Available Balance");
                balanc.setText("Rs. ");
                
        
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        } 
    }//GEN-LAST:event_BalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BALANCEINQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BALANCEINQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BALANCEINQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BALANCEINQUIRY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BALANCEINQUIRY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balance;
    private javax.swing.JButton CANCEL;
    private javax.swing.JLabel Email;
    private javax.swing.JButton NULL1;
    private javax.swing.JButton NULL2;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel SERVICE;
    private javax.swing.JLabel SERVICE1;
    private javax.swing.JLabel TX1;
    private javax.swing.JLabel avail;
    private javax.swing.JLabel balanc;
    private javax.swing.JLabel balance;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton serice;
    public static javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private void getText() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
