/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josep
 */
public class CANCEL extends javax.swing.JFrame {

    /**
     * Creates new form CANCEL
     */
    public CANCEL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NULL1 = new javax.swing.JButton();
        CANCEL = new javax.swing.JButton();
        serice = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        CONFIRM = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        NULL2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(9, 9, 9, 9, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        NULL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL1);
        NULL1.setBounds(1330, 110, 160, 150);

        CANCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELActionPerformed(evt);
            }
        });
        jPanel3.add(CANCEL);
        CANCEL.setBounds(20, 590, 160, 150);

        serice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        serice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sericeActionPerformed(evt);
            }
        });
        jPanel3.add(serice);
        serice.setBounds(1330, 590, 160, 150);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton10);
        jButton10.setBounds(20, 110, 160, 150);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("-");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1300, 580, 50, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(170, 470, 43, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(160, 630, 43, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("-");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(170, 150, 50, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("-");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(170, 310, 43, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(1300, 120, 50, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("-");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(1300, 420, 50, 100);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("-");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(1300, 280, 50, 50);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PicsArt_09-09-03.33.44.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 40, 1024, 680);

        user.setText("user");
        jPanel4.add(user);
        user.setBounds(860, 130, 110, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(203, 21, 1110, 750);

        CONFIRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMActionPerformed(evt);
            }
        });
        jPanel3.add(CONFIRM);
        CONFIRM.setBounds(1330, 430, 160, 150);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton9);
        jButton9.setBounds(20, 430, 160, 150);

        NULL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL2);
        NULL2.setBounds(1330, 270, 160, 150);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(1293, 11, 210, 770);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton7);
        jButton7.setBounds(20, 270, 160, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(9, 11, 220, 770);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 10, 1090, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 730, 1070, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELActionPerformed

    }//GEN-LAST:event_CANCELActionPerformed

    private void sericeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sericeActionPerformed
       
    }//GEN-LAST:event_sericeActionPerformed

    private void CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMActionPerformed

    }//GEN-LAST:event_CONFIRMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CANCEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CANCEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CANCEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CANCEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CANCEL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCEL;
    private javax.swing.JButton CONFIRM;
    private javax.swing.JButton NULL1;
    private javax.swing.JButton NULL2;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton serice;
    public static javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
