/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import UI.Email;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/**
 *
 * @author Marina
 */
public class LOANSTATUS extends javax.swing.JFrame {

    /**
     * Creates new form LOANSTATUS
     */
    public LOANSTATUS() {
        initComponents();
    }
      public LOANSTATUS(String us){
        initComponents();
         user.setText(us);
    }

     public String sendMail(String Email,String Password,String ToEmail,String Subject,String Text){

	String Msg;
    
        final String username = Email;
        final String password = Password;

        Properties props = new Properties();
        props.put("mail.smtp.auth", true);
        props.put("mail.smtp.starttls.enable", true);
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(Email));//ur email
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(Email));//u will send to
            message.setSubject(Subject);
            message.setText(Text);
            Transport.send(message);
            Msg="true";
    	    return Msg;

        } catch (Exception e) {
            return e.toString();
        }
    
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NULL1 = new javax.swing.JButton();
        current = new javax.swing.JButton();
        NULL = new javax.swing.JButton();
        CONFIRM = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SAVING = new javax.swing.JLabel();
        application = new javax.swing.JTextField();
        amt = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        SAVING4 = new javax.swing.JLabel();
        SAVING2 = new javax.swing.JLabel();
        CURRENTS3 = new javax.swing.JLabel();
        CURRENTS2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SAVING1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        appcheck = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(9, 9, 9, 9, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        NULL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL1);
        NULL1.setBounds(1330, 110, 160, 150);

        current.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        current.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentActionPerformed(evt);
            }
        });
        jPanel3.add(current);
        current.setBounds(1330, 430, 160, 150);

        NULL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        NULL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NULLActionPerformed(evt);
            }
        });
        jPanel3.add(NULL);
        NULL.setBounds(1330, 270, 160, 150);

        CONFIRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        CONFIRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMActionPerformed(evt);
            }
        });
        jPanel3.add(CONFIRM);
        CONFIRM.setBounds(1330, 590, 160, 150);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton8);
        jButton8.setBounds(40, 430, 160, 150);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(40, 590, 160, 150);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton10);
        jButton10.setBounds(40, 110, 160, 150);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("-");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1290, 610, 50, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(190, 480, 43, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(190, 640, 43, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("-");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(190, 150, 50, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("-");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(190, 310, 43, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(1290, 160, 50, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("-");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(1290, 450, 50, 100);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("-");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(1290, 310, 50, 50);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        SAVING.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        SAVING.setForeground(new java.awt.Color(204, 255, 204));
        SAVING.setText("Applied Date");
        jPanel4.add(SAVING);
        SAVING.setBounds(130, 390, 340, 71);

        application.setFont(new java.awt.Font("Tahoma", 1, 41)); // NOI18N
        application.setForeground(new java.awt.Color(255, 102, 102));
        application.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationActionPerformed(evt);
            }
        });
        jPanel4.add(application);
        application.setBounds(580, 190, 180, 50);

        amt.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        amt.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(amt);
        amt.setBounds(580, 300, 320, 50);

        status.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(status);
        status.setBounds(580, 510, 440, 50);

        SAVING4.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        SAVING4.setForeground(new java.awt.Color(204, 255, 204));
        SAVING4.setText("Loan Status");
        jPanel4.add(SAVING4);
        SAVING4.setBounds(130, 500, 310, 71);

        SAVING2.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        SAVING2.setForeground(new java.awt.Color(204, 255, 204));
        SAVING2.setText("Application no.");
        jPanel4.add(SAVING2);
        SAVING2.setBounds(130, 180, 380, 71);

        CURRENTS3.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        CURRENTS3.setForeground(new java.awt.Color(255, 255, 204));
        CURRENTS3.setText("CANCEL");
        jPanel4.add(CURRENTS3);
        CURRENTS3.setBounds(30, 600, 200, 72);

        CURRENTS2.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        CURRENTS2.setForeground(new java.awt.Color(255, 255, 204));
        CURRENTS2.setText("CONFIRM");
        jPanel4.add(CURRENTS2);
        CURRENTS2.setBounds(840, 600, 200, 72);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pops.jpg"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(250, 20, 570, 140);

        SAVING1.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        SAVING1.setForeground(new java.awt.Color(204, 255, 204));
        SAVING1.setText("Loan amount");
        jPanel4.add(SAVING1);
        SAVING1.setBounds(130, 290, 340, 71);

        Date.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(Date);
        Date.setBounds(580, 400, 340, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/glossy.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 1050, 710);

        user.setText("jLabel1");
        jPanel4.add(user);
        user.setBounds(860, 130, 41, 16);
        jPanel4.add(Email);
        Email.setBounds(100, 30, 0, 0);
        jPanel4.add(Pass);
        Pass.setBounds(90, 100, 0, 0);
        jPanel4.add(appcheck);
        appcheck.setBounds(90, 30, 0, 0);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(223, 31, 1070, 730);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(1293, 11, 210, 770);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton7);
        jButton7.setBounds(40, 270, 160, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(9, 11, 220, 770);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 10, 1070, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 730, 1070, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentActionPerformed

    }//GEN-LAST:event_currentActionPerformed

    private void NULLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NULLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NULLActionPerformed

    private void CONFIRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMActionPerformed
        Connection con=null;
        PreparedStatement mystmt=null;
        ResultSet rs=null;
        String u;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull", "root", "");
      
            mystmt = con.prepareStatement( "Select * from atmm where username=?");
            mystmt.setString(1, user.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                appcheck.setText(rs.getString("Application_no"));
                int appc=Integer.parseInt(appcheck.getText());
                application.getText();
                int app=Integer.parseInt(application.getText());
                if(app>1&&appc==app){
                Date.setText(rs.getString("Applied_date"));
                amt.setText(rs.getString("Loan_amount"));
                status.setText("Pending");
                }  
                else{
                  application.setText("");
                   JOptionPane.showMessageDialog(this,"INVALID Application no.","Anticipated",JOptionPane.ERROR_MESSAGE);
                }  
                
            }
            else{
                application.setText("");
                status.setText("");
                amt.setText("");
                JOptionPane.showMessageDialog(null,"please try again later");
            }

        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_CONFIRMActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        this.setVisible(false);
        new CANCEL().setVisible(true);  
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void applicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOANSTATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOANSTATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOANSTATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOANSTATUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOANSTATUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONFIRM;
    private javax.swing.JLabel CURRENTS2;
    private javax.swing.JLabel CURRENTS3;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Email;
    private javax.swing.JButton NULL;
    private javax.swing.JButton NULL1;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel SAVING;
    private javax.swing.JLabel SAVING1;
    private javax.swing.JLabel SAVING2;
    private javax.swing.JLabel SAVING4;
    private javax.swing.JLabel amt;
    private javax.swing.JLabel appcheck;
    private javax.swing.JTextField application;
    private javax.swing.JButton current;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel status;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
