
import UI.Email;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josep
 */
public class LOAN extends javax.swing.JFrame {
int o;


    public LOAN() {
        initComponents();
    }
public LOAN(String pass){
        initComponents();
        user.setText(pass);
}
public String sendMail(String Email,String Password,String ToEmail, String Subject,String Text){

	String Msg;
    
        final String username = Email;
        final String password = Password;

        Properties props = new Properties();
        props.put("mail.smtp.auth", true);
        props.put("mail.smtp.starttls.enable", true);
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.setProperty("mail.smtp.ssl.trust", "smtp.gmail.com");

        Session session = Session.getInstance(props, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });

        try {

            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(Email));//ur email
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(Email));//u will send to
            message.setSubject(Subject);
            message.setText(Text);
            Transport.send(message);
            Msg="true";
    	    return Msg;

        } catch (Exception e) {
            return e.toString();
        }
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NULL1 = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SAVING = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        loan = new javax.swing.JTextField();
        CURRENTS3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        application = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rec = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        CURRENTS4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        not = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        akdj = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        NULL2 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(9, 9, 9, 9, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        NULL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL1);
        NULL1.setBounds(1330, 110, 160, 150);

        confirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel3.add(confirm);
        confirm.setBounds(1330, 600, 160, 150);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton10);
        jButton10.setBounds(40, 110, 160, 150);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("-");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1290, 610, 50, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(190, 470, 43, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(190, 630, 43, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("-");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(190, 150, 50, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("-");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(190, 310, 43, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(1290, 160, 50, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("-");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(1290, 450, 50, 100);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("-");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(1290, 310, 50, 50);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Loan Amount");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(20, 220, 274, 60);

        SAVING.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        SAVING.setForeground(new java.awt.Color(204, 255, 204));
        SAVING.setText("Application no.");
        jPanel4.add(SAVING);
        SAVING.setBounds(20, 130, 280, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("No. of years");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 320, 263, 50);

        year.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        year.setForeground(new java.awt.Color(0, 102, 153));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel4.add(year);
        year.setBounds(460, 330, 160, 40);

        loan.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        loan.setForeground(new java.awt.Color(0, 102, 153));
        loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanActionPerformed(evt);
            }
        });
        jPanel4.add(loan);
        loan.setBounds(460, 230, 160, 40);

        CURRENTS3.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        CURRENTS3.setForeground(new java.awt.Color(255, 255, 153));
        CURRENTS3.setText("LOAN STATUS");
        jPanel4.add(CURRENTS3);
        CURRENTS3.setBounds(20, 590, 270, 72);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Monthly Payment");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(20, 410, 330, 60);

        application.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        application.setForeground(new java.awt.Color(255, 153, 153));
        jPanel4.add(application);
        application.setBounds(460, 130, 160, 50);

        month.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        month.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(month);
        month.setBounds(450, 420, 180, 40);

        total.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 204));
        jPanel4.add(total);
        total.setBounds(450, 520, 180, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Total Payment");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 520, 274, 50);

        jLabel34.setFont(new java.awt.Font("STLiti", 1, 100)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 153, 0));
        jLabel34.setText("%");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(890, 10, 90, 100);

        rec.setColumns(20);
        rec.setRows(5);
        rec.setText("\n");
        jScrollPane2.setViewportView(rec);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(630, 110, 420, 500);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rs.");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(380, 520, 60, 50);

        CURRENTS4.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        CURRENTS4.setForeground(new java.awt.Color(255, 255, 153));
        CURRENTS4.setText("CONFIRM");
        jPanel4.add(CURRENTS4);
        CURRENTS4.setBounds(860, 600, 200, 72);

        jLabel31.setFont(new java.awt.Font("STLiti", 1, 70)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 51, 51));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mini.gif"))); // NOI18N
        jPanel4.add(jLabel31);
        jLabel31.setBounds(800, 20, 100, 90);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rs.");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(380, 230, 60, 40);

        jLabel32.setFont(new java.awt.Font("STLiti", 1, 45)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 204, 255));
        jLabel32.setText("Avail Loan with Interest rate Of just");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(110, 30, 700, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rs.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(380, 420, 60, 40);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(10, 590, 620, 10);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/glossy.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 1050, 710);

        user.setText("user");
        jPanel4.add(user);
        user.setBounds(860, 130, 110, 40);
        jPanel4.add(Email);
        Email.setBounds(570, 680, 0, 0);
        jPanel4.add(Pass);
        Pass.setBounds(450, 690, 0, 0);
        jPanel4.add(account);
        account.setBounds(710, 670, 0, 0);

        not.setText("Under Verification");
        jPanel4.add(not);
        not.setBounds(440, 670, 102, 16);

        status.setText("approval pending");
        jPanel4.add(status);
        status.setBounds(700, 670, 98, 16);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(223, 31, 1070, 730);

        akdj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        akdj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akdjActionPerformed(evt);
            }
        });
        jPanel3.add(akdj);
        akdj.setBounds(1330, 440, 160, 150);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton9);
        jButton9.setBounds(40, 430, 160, 150);

        NULL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(NULL2);
        NULL2.setBounds(1330, 270, 160, 150);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(40, 590, 160, 150);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(1293, 11, 210, 770);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton7);
        jButton7.setBounds(40, 270, 160, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(9, 11, 220, 770);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 10, 1090, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 730, 1070, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        Connection con=null;
        PreparedStatement mystmt=null;
        ResultSet rs=null;     
         int lo=Integer.parseInt(loan.getText());
           int ye=Integer.parseInt(year.getText());
        if(lo>9999){
            if(lo<3000000){
                if(ye<5){
          try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull", "root", "");
            mystmt = con.prepareStatement( "Select * from atmm where username=?");
            mystmt.setString(1, user.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
             Email.setText(rs.getString("EmailID"));
             Pass.setText(rs.getString("EmailPassword"));
             account.setText(rs.getString("accountholder"));
             not.setText(rs.getString("Application_no"));
             int app=Integer.parseInt(not.getText());
             
             if(app<5)
             {
                   
              Random rand=new Random();
              o = rand.nextInt(99999);
              String on=String.valueOf(o);
              int one=Integer.parseInt(loan.getText());
              int two=Integer.parseInt(year.getText());
              double x = 5*one/100; 
              String mon = String.valueOf((one+x)/(12*two)); 
              month.setText(mon);
              String tot = String.valueOf(one+x);
              total.setText(tot);
              application.setText(on);
           
             SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                     Date date=new Date();  
                    String strDate=sdf.format(date);
                    SimpleDateFormat sd=new SimpleDateFormat("hh:mm:ss aa");
                    String strTime=sd.format(date);
                
                    mystmt = con.prepareStatement( "insert into loann values(?,?,?,?,?,?)");
                    mystmt.setString(1, user.getText());
                    mystmt.setString(2, application.getText());
                    mystmt.setString(3, loan.getText());
                    mystmt.setString(4, strDate);
                    mystmt.setString(5, strTime);
                     mystmt.setString(6, "Pending");
                    mystmt.executeUpdate();
          
              rec.setText("\t\t    SWIZZ BANK\n\n"+"\t                       Loan Management System"
                  +"\n   ======================================================\n"
                +"\n\n   Date                                                             "+strDate
                +"\n\n   Account number                                          "+user.getText()
                +"\n\n   Name                                                           "+account.getText()
                +"\n\n   Application No.                                            "+application.getText()
                +"\n\n   Loan amount                                               "+loan.getText()
                +"\n\n   Interest percentage                                     5%"
                +"\n\n   Monthly payment                                          "+month.getText()
                +"\n\n   Total payment                                              "+total.getText()
              +"\n\n\n   =====================================================\n"
                +"\n     You will be notified once when your loan has been processed by the bank \n\n"
                +"\n\t\tTHANK YOU");
               JOptionPane.showMessageDialog(this,"loan has been successfully applied please use your application number for future reference");
                 String EMAIL = Email.getText();
                String PW=Pass.getText();
                String To=Email.getText();
                String SUBJECT="SWIZZ Bank--(Loan) ";
                String MESGE="Dear Custmer, your loan has been successfully applied for the application number "+application.getText()+" use this application number for future reference. \n\n\nTHANK YOU  \n\nREGARDS  SWIZZ BANK";
                String DATA=new Email().sendMail(EMAIL, PW, To, SUBJECT, MESGE);
                System.out.println(DATA);
                 if(DATA.equals("true")){ 
                 }
                else{
               JOptionPane.showMessageDialog(this,"An Error Occured While Sending Confirmation Email ","Error",JOptionPane.ERROR_MESSAGE);
               this.setVisible(false);
               new CANCEL().setVisible(true);
               dispose();
               }
                    String query="UPDATE atmm SET Application_no=? WHERE username=?";
            mystmt= con.prepareStatement(query);
            mystmt.setString(1, application.getText());
            mystmt.setString(2, user.getText());
            mystmt.executeUpdate();
            
                  String quer="UPDATE atmm SET Loan_amount=? WHERE username=?";
            mystmt= con.prepareStatement(quer);
            mystmt.setString(1, loan.getText());
            mystmt.setString(2, user.getText());
            mystmt.executeUpdate();
            
             String que="UPDATE atmm SET Applied_date=? WHERE username=?";
            mystmt= con.prepareStatement(que);
            mystmt.setString(1, strDate);
            mystmt.setString(2, user.getText());
            mystmt.executeUpdate();
                   
              }
             else{
             JOptionPane.showMessageDialog(this,"Loan cannot be appllied multiple times","Loan management ",JOptionPane.ERROR_MESSAGE);
             loan.setText("");
             year.setText("");
              String EMAIL = Email.getText();
                String PW=Pass.getText();
                String To=Email.getText();
                String SUBJECT="SWIZZ Bank--(Loan) ";
               String MESGE="Dear customer, you cannot apply loan multiple times, please use your loan application number for future reference\n\n\nTHANK YOU \n\nREGARDS SWIZZ BANKs";

                 String DATA=new Email().sendMail(EMAIL, PW, To, SUBJECT, MESGE);
                System.out.println(DATA);
                 if(DATA.equals("true")){
                     
                 }
                else{
               JOptionPane.showMessageDialog(this,"An Error Occured While Sending Email Information ","Error",JOptionPane.ERROR_MESSAGE);
               this.setVisible(false);
               new CANCEL().setVisible(true);
               dispose();
               }
                     }
            
            }          
             else{
                     JOptionPane.showMessageDialog(this,"loan application failed!! please try again later");
                     loan.setText("");
                     year.setText("");
                      this.setVisible(false);
            new CANCEL().setVisible(true);
                     }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
                }
                else{
                JOptionPane.showMessageDialog(this,"Loan can be applied for the Maximum time period of 5 years only","Loan management ",JOptionPane.ERROR_MESSAGE);
                 loan.setText("");
                 year.setText("");
                  month.setText("");
                   total.setText("");
                   application.setText("");
                    }
      
        }
         else{
           JOptionPane.showMessageDialog(this,"Maximum amount for applying loan is 3000000 ","Loan management ",JOptionPane.ERROR_MESSAGE);
        loan.setText("");
        year.setText("");
        month.setText("");
        total.setText("");
        application.setText("");
        }
        
        }
        else{
           JOptionPane.showMessageDialog(this,"Minimum amount for applying loan is 10000 ","Loan management ",JOptionPane.ERROR_MESSAGE);
        loan.setText("");
        year.setText("");
        month.setText("");
        total.setText("");
        application.setText("");
        }
        
        
      
    }//GEN-LAST:event_confirmActionPerformed

    private void akdjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akdjActionPerformed
    
    }//GEN-LAST:event_akdjActionPerformed

    private void loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
     String  us=user.getText();
     this.setVisible(false);
     new LOANSTATUS(us).setVisible(true);
     dispose();
                        
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CURRENTS3;
    private javax.swing.JLabel CURRENTS4;
    private javax.swing.JLabel Email;
    private javax.swing.JButton NULL1;
    private javax.swing.JButton NULL2;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel SAVING;
    private javax.swing.JLabel account;
    private javax.swing.JButton akdj;
    private javax.swing.JLabel application;
    private javax.swing.JButton confirm;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField loan;
    private javax.swing.JLabel month;
    private javax.swing.JLabel not;
    private javax.swing.JTextArea rec;
    private javax.swing.JLabel status;
    private javax.swing.JLabel total;
    public static javax.swing.JLabel user;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}

