
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marina
 */

public class SERVICE extends javax.swing.JFrame{

    /**
     * Creates new form SERVICE
     */
    public SERVICE() {
        initComponents();
    }
    
public SERVICE(String us){
        initComponents();
         user.setText(us);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        UPDATEMOBILENO = new javax.swing.JButton();
        WITHDRAWAL = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        deposit = new javax.swing.JButton();
        LOAN_APPLICATION = new javax.swing.JButton();
        LinkPAN = new javax.swing.JButton();
        BALANCEINQUIRY1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        PIN_CHANGE = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(9, 9, 9, 9, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        UPDATEMOBILENO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        UPDATEMOBILENO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEMOBILENOActionPerformed(evt);
            }
        });
        jPanel3.add(UPDATEMOBILENO);
        UPDATEMOBILENO.setBounds(1330, 600, 160, 150);

        WITHDRAWAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        WITHDRAWAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WITHDRAWALActionPerformed(evt);
            }
        });
        jPanel3.add(WITHDRAWAL);
        WITHDRAWAL.setBounds(1330, 280, 160, 150);

        transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        jPanel3.add(transfer);
        transfer.setBounds(1330, 120, 160, 150);

        deposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositActionPerformed(evt);
            }
        });
        jPanel3.add(deposit);
        deposit.setBounds(40, 110, 160, 150);

        LOAN_APPLICATION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        LOAN_APPLICATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOAN_APPLICATIONActionPerformed(evt);
            }
        });
        jPanel3.add(LOAN_APPLICATION);
        LOAN_APPLICATION.setBounds(40, 590, 160, 150);

        LinkPAN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        LinkPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkPANActionPerformed(evt);
            }
        });
        jPanel3.add(LinkPAN);
        LinkPAN.setBounds(40, 430, 160, 150);

        BALANCEINQUIRY1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        BALANCEINQUIRY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BALANCEINQUIRY1ActionPerformed(evt);
            }
        });
        jPanel3.add(BALANCEINQUIRY1);
        BALANCEINQUIRY1.setBounds(1330, 440, 160, 150);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("-");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1290, 610, 50, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(190, 320, 43, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(190, 640, 43, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("-");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(190, 160, 43, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("-");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(190, 480, 43, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("-");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(1290, 460, 50, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(1290, 170, 50, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("-");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(1290, 290, 50, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("DEPOSIT");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(30, 120, 180, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("BALANCE INQUIRY");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(670, 430, 380, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("WITHDRAWAL");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(740, 270, 300, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("PIN CHANGE");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(30, 270, 260, 72);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 204));
        jLabel20.setText("LINK PAN CARD");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(30, 420, 330, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("LOAN APPLICATION");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 590, 408, 72);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 204));
        jLabel7.setText("Select Service");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(440, 120, 221, 45);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 204));
        jLabel22.setText("UPDATE MOBILE NO.");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(642, 570, 400, 100);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("TRANSFER");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(830, 120, 210, 72);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pops.jpg"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(250, 10, 570, 130);

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/glossy.png"))); // NOI18N
        jPanel4.add(jlabel);
        jlabel.setBounds(10, 10, 1040, 700);

        user.setText("\n");
        jPanel4.add(user);
        user.setBounds(560, 270, 100, 16);
        jPanel4.add(Email);
        Email.setBounds(820, 40, 0, 0);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(230, 40, 1063, 720);

        PIN_CHANGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        PIN_CHANGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN_CHANGEActionPerformed(evt);
            }
        });
        jPanel3.add(PIN_CHANGE);
        PIN_CHANGE.setBounds(40, 270, 160, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(9, 11, 220, 770);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(230, 10, 1060, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 740, 1070, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(1290, 10, 230, 770);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void LOAN_APPLICATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOAN_APPLICATIONActionPerformed
       String us = user.getText();               
       this.setVisible(false);
       new LOAN(us).setVisible(true);
       dispose();
    }//GEN-LAST:event_LOAN_APPLICATIONActionPerformed

    private void LinkPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkPANActionPerformed
        String us=user.getText();
        this.setVisible(false);
        new PAN(us).setVisible(true);
    }//GEN-LAST:event_LinkPANActionPerformed

    private void PIN_CHANGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN_CHANGEActionPerformed
                                  
                String us=user.getText();      
                this.setVisible(false);
                new oldpin(us).setVisible(true);
                dispose();
           
    }//GEN-LAST:event_PIN_CHANGEActionPerformed

    private void depositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositActionPerformed
       String us=user.getText();
       this.setVisible(false);
       new DEPOSITT(us).setVisible(true);
       dispose();
    }//GEN-LAST:event_depositActionPerformed

    private void UPDATEMOBILENOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEMOBILENOActionPerformed
     String us=user.getText();
     this.setVisible(false);
     new updatemobile(us).setVisible(true);
     dispose();
    }//GEN-LAST:event_UPDATEMOBILENOActionPerformed

    private void BALANCEINQUIRY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BALANCEINQUIRY1ActionPerformed
        String us=user.getText();
        this.setVisible(false);
        new BALANCEINQUIRY(us).setVisible(true);   
        
       
    }//GEN-LAST:event_BALANCEINQUIRY1ActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
       String us=user.getText();
       this.setVisible(false);
       new TRANSFERR(us).setVisible(true);
       dispose();
    }//GEN-LAST:event_transferActionPerformed

    private void WITHDRAWALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WITHDRAWALActionPerformed
 String us=user.getText();
       this.setVisible(false);
       new WITHDRAWAL(us).setVisible(true);
       dispose();
    }//GEN-LAST:event_WITHDRAWALActionPerformed

    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SERVICE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BALANCEINQUIRY1;
    private javax.swing.JLabel Email;
    public static javax.swing.JButton LOAN_APPLICATION;
    public static javax.swing.JButton LinkPAN;
    public static javax.swing.JButton PIN_CHANGE;
    private javax.swing.JButton UPDATEMOBILENO;
    private javax.swing.JButton WITHDRAWAL;
    private javax.swing.JButton deposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlabel;
    private javax.swing.JButton transfer;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    private Object login() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
