
import UI.Email;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josep
 */
public class TRANSFERR extends javax.swing.JFrame {

    /**
     * Creates new form TRANSFERR
     */
    public TRANSFERR() {
        initComponents();
    }
    public TRANSFERR(String us){
        initComponents();
         user.setText(us);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        CONFIRMDEPOSIT = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        account = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        payee = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        depositor = new javax.swing.JTextField();
        bal = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(9, 9, 9, 9, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        CONFIRMDEPOSIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        CONFIRMDEPOSIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMDEPOSITActionPerformed(evt);
            }
        });
        jPanel3.add(CONFIRMDEPOSIT);
        CONFIRMDEPOSIT.setBounds(1330, 560, 160, 150);

        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(btn0);
        btn0.setBounds(1330, 80, 160, 150);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(btn1);
        btn1.setBounds(1330, 400, 160, 150);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton8);
        jButton8.setBounds(40, 400, 160, 150);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(jButton9);
        jButton9.setBounds(40, 80, 160, 150);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("-");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1290, 580, 50, 100);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("-");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(190, 450, 43, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("-");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(190, 600, 43, 50);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("-");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(190, 130, 43, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("-");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(190, 280, 43, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("-");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(1290, 120, 50, 60);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("-");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(1290, 420, 50, 100);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Rs.");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(340, 430, 70, 72);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("Enter the Amount to be Deposited");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(120, 340, 770, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Enter the Account number of the PAYEE");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(120, 150, 890, 80);

        amt.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        amt.setForeground(new java.awt.Color(0, 102, 153));
        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });
        jPanel4.add(amt);
        amt.setBounds(420, 440, 240, 60);

        account.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        account.setForeground(new java.awt.Color(0, 102, 153));
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });
        jPanel4.add(account);
        account.setBounds(420, 250, 250, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("CANCEL");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(30, 520, 200, 72);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 38)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("CONFIRM");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(840, 520, 200, 72);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pops.jpg"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(250, 20, 570, 140);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/glossy.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 1040, 640);

        payee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payeeActionPerformed(evt);
            }
        });
        jPanel4.add(payee);
        payee.setBounds(926, 240, 60, 22);

        user.setText("jLabel1");
        jPanel4.add(user);
        user.setBounds(820, 170, 41, 16);
        jPanel4.add(Email);
        Email.setBounds(950, 100, 6, 22);

        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        jPanel4.add(balance);
        balance.setBounds(410, 610, 6, 22);
        jPanel4.add(password);
        password.setBounds(130, 610, 6, 22);
        jPanel4.add(depositor);
        depositor.setBounds(430, 170, 6, 22);
        jPanel4.add(bal);
        bal.setBounds(900, 30, 0, 0);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(230, 70, 1063, 661);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jPanel3.add(btn2);
        btn2.setBounds(1330, 240, 160, 150);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("-");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(1290, 280, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(1293, 11, 210, 770);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(40, 240, 160, 150);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smlbutton.jpg"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(40, 560, 160, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(9, 11, 220, 770);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(220, 10, 1090, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/border.jpg"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(230, 730, 1070, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONFIRMDEPOSITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMDEPOSITActionPerformed
        Connection con=null;
        PreparedStatement mystmt=null;
        ResultSet rs=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull", "root", "");
            mystmt = con.prepareStatement( "Select * from atmm where username=?");
            mystmt.setString(1, user.getText());
            rs = mystmt.executeQuery();
            if(rs.next()){
                Email.setText(rs.getString("EmailID"));
                password.setText(rs.getString("EmailPassword"));
                balance.setText(rs.getString("Balance"));
                int ba=Integer.parseInt(balance.getText());
                int am=Integer.parseInt(amt.getText());
                int acch=Integer.parseInt(user.getText());
                int acc=Integer.parseInt(account.getText());

                mystmt = con.prepareStatement( "Select * from atmm where username=?");
                mystmt.setString(1, account.getText());
                rs = mystmt.executeQuery();
                if(rs.next()){
                    bal.setText(rs.getString("Balance"));
                    int paybal=Integer.parseInt(bal.getText());

                    if(acch!=acc){
                        if(ba>am){
                            if(am>499&&am<75000){

                                SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
                                Date date=new Date();
                                String strDate=sdf.format(date);
                                SimpleDateFormat sd=new SimpleDateFormat("hh:mm:ss aa");
                                String strTime=sd.format(date);

                                mystmt = con.prepareStatement( "insert into transferr values(?,?,?,?,?)");
                                mystmt.setString(1, user.getText());
                                mystmt.setString(2, account.getText());
                                mystmt.setString(3, amt.getText());
                                mystmt.setString(4, strDate);
                                mystmt.setString(5, strTime);
                                mystmt.executeUpdate();
                                String usu = String.valueOf(paybal+am);
                                String usee = String.valueOf(ba-am);

                                payee.setText(usu);
                                depositor.setText(usee);
                                String dep=depositor.getText();
                                String pay=payee.getText();
                                String amtt=amt.getText();

                                String query="UPDATE atmm SET Balance=? WHERE username=?";
                                mystmt= con.prepareStatement(query);
                                mystmt.setString(1, payee.getText());
                                mystmt.setString(2, account.getText());
                                mystmt.executeUpdate();

                                String quer="UPDATE atmm SET Balance=? WHERE username=?";
                                mystmt= con.prepareStatement(quer);
                                mystmt.setString(1, depositor.getText());
                                mystmt.setString(2, user.getText());
                                mystmt.executeUpdate();
                                JOptionPane.showMessageDialog(null,"Transaction Successfull");

                                String EMAIL = Email.getText();
                                String PW=password.getText();
                                String To=Email.getText();
                                String SUBJECT="SWIZZ Bank(Transaction) ";
                                String MESGE="Dear Custmer,your account has been Debited of Rs."+amtt+" and transfered to account number xxxxxxxxx your avilable balance is Rs. "+dep+"\n\n\nTHANK YOU \n\nREGARDS  SWIZZ BANK";

                                String DATA=new Email().sendMail(EMAIL, PW, To, SUBJECT, MESGE);
                                System.out.println(DATA);
                                if(DATA.equals("true")){

                                }
                                else{
                                    JOptionPane.showMessageDialog(this,"An Error Occured While Sending Confirmation Email ","Error",JOptionPane.ERROR_MESSAGE);
                                    this.setVisible(false);
                                    new CANCEL().setVisible(true);
                                    dispose();
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(this,"Maximum transferable amount is Rs.75000 and Min Amount of tranfer is Rs. 500","Transaction Failed",JOptionPane.ERROR_MESSAGE);
                                account.setText("");
                                amt.setText("");
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(this,"Insufficient Balance","Transaction Failed",JOptionPane.ERROR_MESSAGE);
                            account.setText("");
                            amt.setText("");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this,"Please provide a different Account no.","Transaction Failed",JOptionPane.ERROR_MESSAGE);
                        account.setText("");
                        amt.setText("");
                    }

                }
                else{
                    JOptionPane.showMessageDialog(this,"Please Check the Entered Account number","Transaction Failed ",JOptionPane.ERROR_MESSAGE);
                    account.setText("");
                    amt.setText("");
                }

            }
            else{
                JOptionPane.showMessageDialog(this,"Transaction couldn't be completed Please check your entered details and try again","Transaction failed",JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
                new CANCEL().setVisible(true);
                dispose();
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_CONFIRMDEPOSITActionPerformed

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amtActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed

    }//GEN-LAST:event_accountActionPerformed

    private void payeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payeeActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setVisible(false);
        new CANCEL().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TRANSFERR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TRANSFERR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TRANSFERR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TRANSFERR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TRANSFERR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONFIRMDEPOSIT;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField account;
    private javax.swing.JTextField amt;
    private javax.swing.JLabel bal;
    private javax.swing.JTextField balance;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JTextField depositor;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField password;
    private javax.swing.JTextField payee;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
